# Generated by Django 4.0.6 on 2022-07-25 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_component', models.CharField(choices=[('Teclado', 'Teclado'), ('Raton', 'Raton'), ('Monitor', 'Monitor'), ('Altavoces', 'Altavoces'), ('Placabase', 'Placabase'), ('Procesador', 'Procesador')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contadorComputadoras', models.IntegerField(default=1)),
                ('total_costo', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DispositivoDeEntrada',
            fields=[
                ('componente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computer.componente')),
                ('marca', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
            ],
            bases=('computer.componente',),
        ),
        migrations.CreateModel(
            name='DispositivoDeSalida',
            fields=[
                ('componente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computer.componente')),
                ('marca', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
            ],
            bases=('computer.componente',),
        ),
        migrations.CreateModel(
            name='DispositivoInterno',
            fields=[
                ('componente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computer.componente')),
                ('marca', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
            ],
            bases=('computer.componente',),
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contadorOrdenes', models.IntegerField()),
                ('total_costo', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('computadoras', models.ManyToManyField(related_name='computadoras', to='computer.computadora')),
            ],
        ),
        migrations.CreateModel(
            name='Altavoz',
            fields=[
                ('dispositivodesalida_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computer.dispositivodesalida')),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('computer.dispositivodesalida',),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('dispositivodesalida_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computer.dispositivodesalida')),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('computer.dispositivodesalida',),
        ),
        migrations.CreateModel(
            name='PlacaBase',
            fields=[
                ('dispositivointerno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computer.dispositivointerno')),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('computer.dispositivointerno',),
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('dispositivointerno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computer.dispositivointerno')),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('computer.dispositivointerno',),
        ),
        migrations.CreateModel(
            name='Raton',
            fields=[
                ('dispositivodeentrada_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computer.dispositivodeentrada')),
                ('contadorRatones', models.IntegerField()),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('computer.dispositivodeentrada',),
        ),
        migrations.CreateModel(
            name='Teclado',
            fields=[
                ('dispositivodeentrada_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computer.dispositivodeentrada')),
                ('contadorTeclados', models.IntegerField()),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('computer.dispositivodeentrada',),
        ),
        migrations.AddField(
            model_name='computadora',
            name='altavoz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.altavoz'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.monitor'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='placabase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.placabase'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='procesador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.procesador'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='raton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.raton'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='teclado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.teclado'),
        ),
    ]
