# Generated by Django 4.0.6 on 2022-07-19 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ObraDeArte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreObra', models.CharField(max_length=100)),
                ('tipoDeObra', models.CharField(max_length=100)),
                ('fechaCreacion', models.CharField(max_length=10)),
                ('valorEstimado', models.IntegerField()),
                ('fotosVideos', models.CharField(max_length=100)),
                ('autores', models.ManyToManyField(to='gallery.autores')),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePortafolio', models.CharField(max_length=100)),
                ('obrasDeArte', models.ManyToManyField(to='gallery.obradearte')),
            ],
        ),
        migrations.CreateModel(
            name='Exposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreExpo', models.CharField(max_length=100)),
                ('fechaExpo', models.CharField(max_length=100)),
                ('lugarExpo', models.CharField(max_length=100)),
                ('descripcionExpo', models.CharField(max_length=100)),
                ('portafolioExpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.portafolio')),
            ],
        ),
    ]
